### ISSUE TITLE
Directive should work with no options passed in

### ISSUE THREAD

**Issue by benjamincharity** [benjamincharity/angular-flickity#29]
Currently the directive chokes if it doesn't receive an object.

**Comment by diegopamio** [comment]
I still get "Unexpected end of JSON input " when no options are provided.

**Comment by benjamincharity** [comment]
Thanks for calling this out @diegopamio, I was able to reproduce so I am reopening. Should be a quick fix so I'll try to get to it after work 👍

**Comment by benjamincharity** [comment]
Fixed in 2.0.1: https://github.com/benjamincharity/angular-flickity/releases/tag/v2.0.1
