### ISSUE TITLE
staticClick event data does not surface all parameters

### ISSUE THREAD

**Issue by kgamble** [benjamincharity/angular-flickity#31]
It's difficult to make use of the staticClick event because it does not provide the parameters of the event from the underlying API (pointer, cellElement, cellIndex).  These are needed to determine which item was clicked.  Is there a way to retrieve these using the existing code?

**Comment by benjamincharity** [comment]
Hey @kgamble I am very sorry this fell through the cracks for so long. I had apparently unsubscribed from my own repo's events (didn't know that was possible!).

Anyway, you call out a _very_ good point. Currently, most of those parameters are not being passed with the `$emit`. This was definitely an oversight and I am already working on a fix. Should have something this weekend.

**Comment by benjamincharity** [comment]
I was actually able to find some time to knock this out today.

Fix: https://github.com/benjamincharity/angular-flickity/pull/35

Feel free to check the fix out from `master`. I want to do a little more testing before I tag for release, but it should happen tonight or tomorrow.

**Comment by benjamincharity** [comment]
1.1.0 was just release which includes this fix: https://github.com/benjamincharity/angular-flickity/releases/tag/v1.1.0
