### ISSUE TITLE
v2.0.1 - Options on bc-flickity attribute are completely ignored

### ISSUE THREAD

**Issue by luigimannoni** [benjamincharity/angular-flickity#57]
**Issue:** 
Assigning options from the constructor and passing them on the directive argument on the template does not work and ignores all the settings.

**Code example (ES6):**
```javascript
export default class CarouselController {

  constructor(FlickityService) {
    this.flickityOptions = {
      cellSelector: '.child-slide',
      setGallerySize: true,
      prevNextButtons: false,
      imagesLoaded: true,
      pageDots: false,
      wrapAround: true
    };
  }
}
```
```pug
.carousel-component(bc-flickity="{{ $ctrl.flickityOptions }}")
  .child-slide(ng-repeat="item in $ctrl.items")
    image-component(image="item.image", url="item.url")
```

**Result**:
`prevNextButtons`, `imagesLoaded`, `pageDots`, `wrapAround` options are ignored and the default setting is always displayed

**Demo (forked from your demo):**
http://plnkr.co/edit/sU6VoIz7UyODu8Rcxs0k?p=preview

**Workaround:**
Downgrade to v2.0.0

**Comment by benjamincharity** [comment]
Apologies for this, @luigimannoni. This was a simple developer error on my part ☹️ . I have pushed a fix out for this: https://github.com/benjamincharity/angular-flickity/releases/tag/v2.0.2.

Adding unit tests for this module is next on my list of priorities which should help cut out these simple errors.

Thanks for bringing this to my attention!
