### ISSUE TITLE
Bower Resolution Issue

### ISSUE THREAD

**Issue by parmarsanjay** [benjamincharity/angular-flickity#58]
I am trying to use Angular-Flickity but running into some version issue. I have specified following in my bower.json file.

  "angular-flickity": "2.0.0",

I haven't explicitly specified "flickity" version in bower.json. 

when I run bower install, I see following.

angular-flickity#2.0.0 web/src/main/webapp/bower_components/angular-flickity
├── angular#1.5.8
└── flickity#1.2.1

It's resolving to 1.2.1 version of flickity. 

Do I need to explicitly specifiy flickity version in my bower.json?

**Comment by benjamincharity** [comment]
Hey there @parmarsanjay, sorry you're having issues with this.

How recently did you install angular-flickity? Around 6 hours ago I was doing some cleanup and noticed that I had not bumped the Flickity version number in the bower config but I had in the NPM config.  I just tagged another release in case you weren't getting that fix: https://github.com/benjamincharity/angular-flickity/releases/tag/v2.0.3

Try installing angular-flickity v2.0.3 and see if that solves the issue.

```
  "angular-flickity": "^2.0.3"
```

**Comment by parmarsanjay** [comment]
Awesome. Thanks for the quick turnaround. This fixed the issue. 

Cheers,
Sanjay

**Comment by benjamincharity** [comment]
Perfect. Happy coding! 🚀
