### ISSUE TITLE
Prev / Next Button Issue

### ISSUE THREAD

**Issue by parmarsanjay** [benjamincharity/angular-flickity#59]
I am trying to use multiple sliders of Flickity in my single view. For some reason, Prev and Next Arrows are not showing for all the Flickity sliders. It only shows up for one of the Flickity slider and where it shows up, it ends up controller different slider. 
Any idea?

**Comment by benjamincharity** [comment]
Hard to say exactly without seeing an example or CodePen etc.

If I had to guess it sounds like maybe you aren't specifying the [instance ID on the prev/next button](https://github.com/benjamincharity/angular-flickity#bc-flickity-next)?

Also, maybe check out [this demo](http://plnkr.co/edit/gFwwJf?p=preview). The second and third slider both have external buttons. Possibly you can see a difference between the demo and your code.

**Comment by parmarsanjay** [comment]
I am adding the instance ID. I am not adding external prev / next buttons. I am referring to the prev/next arrows, which come by default. One thing i have observed is, it works fine in my deveopment. It doesn't work in production mode where I do useRef for JS file and minified HTML files. Any pointer will be helpful to troubleshoot this.

**Comment by benjamincharity** [comment]
Ahh I see.. That is even more odd since that is part of the core Flickity library and not generated by this module. 

Nothing logical is jumping out as a possible cause. But if you are able to reproduce in a place where I can see, I'd be more than happy to take a look.

**Comment by parmarsanjay** [comment]
Thanks, Ben. I will send you email on my server where this application is running. Sorry, I am new to AngularJs world :-). Just need some pointers to troubleshoot.

**Comment by parmarsanjay** [comment]
One thing i found is, all the arrows for prev/next of different carousels are getting stacked on each other. That's the reason, I only see one set of prev/next arrows.

**Comment by benjamincharity** [comment]
Yep. Just was looking at that. The arrows are positioned absolutely so if you add `position: relative` to each container, it will layout the arrows correctly.

**Comment by parmarsanjay** [comment]
Thanks, Ben. The thing is it's working in Dev mode. BTW, how do i override the position element?

**Comment by benjamincharity** [comment]
The arrows are styled so they lay out on the left and right, centered vertically inside the first parent container that has `position` set as a style. So you just need to add some CSS to make sure this is the case.

For instance, if this was your markup:

```
  <div class="example">
        <div
            class="demo__slides"
            bc-flickity="{{ flickityOptions }}"
            bc-flickity-id="demoId1"
        >
            <figure class="demo__slide" data-ng-repeat="slide in slides track by $index">
                <img data-ng-src="{{ ::slide }}" alt="" />
            </figure>
        </div>
  </div>
```

you could add the position to the parent like this:

```css
.example {
  position: relative;
}
```

This makes sure the arrows are centered vertically according to this container. Open up the Chrome dev tools and take a look at the styles in this demo: http://plnkr.co/edit/gFwwJf?p=preview

**Comment by parmarsanjay** [comment]
Awesome. You made my day 👍 .  Thanks a bunch.

**Comment by benjamincharity** [comment]
Glad I could help!

**Comment by parmarsanjay** [comment]
One quick question on packaging. I am only specifying following in my bower.json file.

"angular-flickity": "2.0.3",

and to use the minified versions, this is what i do.

"angular-flickity": {
      "main": [
        "dist/angular-flickity.min.js"
      ]
    },
    "flickity": {
      "main": [
        "dist/flickity.pkgd.min.js",
        "dist/flickity.min.css"
      ]
    },

Everything works great. It's just that, when i Look at my index.html after running wiredep, I see following files in there, which i guess are not needed because I am already using pkgd.min.js. How do i tell Bower to not include these files?

<script src="bower_components/desandro-matches-selector/matches-selector.js"></script>
    <script src="bower_components/ev-emitter/ev-emitter.js"></script>
    <script src="bower_components/fizzy-ui-utils/utils.js"></script>
    <script src="bower_components/get-size/get-size.js"></script>
    <script src="bower_components/unipointer/unipointer.js"></script>
    <script src="bower_components/tap-listener/tap-listener.js"></script>
    <script src="bower_components/unidragger/unidragger.js"></script>
<script src="bower_components/imagesloaded/imagesloaded.js"></script>

These are flickity dependencies.  

├─┬ angular-flickity#2.0.3 (latest is 2.1.0)
│ ├── angular#1.5.8 (1.6.0-rc.0 available)
│ ├─┬ flickity#2.0.5
│ │ ├── desandro-matches-selector#2.0.1
│ │ ├── ev-emitter#1.0.3
│ │ ├─┬ fizzy-ui-utils#2.0.3
│ │ │ └── desandro-matches-selector#2.0.1
│ │ ├── get-size#2.0.2
│ │ ├─┬ tap-listener#2.0.0
│ │ │ └─┬ unipointer#2.1.0
│ │ │   └── ev-emitter#1.0.3
│ │ └─┬ unidragger#2.1.0
│ │   └── unipointer#2.1.0
│ └─┬ imagesloaded#4.1.1
│   └── ev-emitter#1.0.3

**Comment by parmarsanjay** [comment]
Never mind. Found the solution. Doing following to avoid installing unwanted files.

"flickity": {
      "main": [
        "dist/flickity.pkgd.min.js",
        "dist/flickity.min.css"
      ],
      ## "dependencies" : {}
    },
