### ISSUE TITLE
Sourcemaps included in dist min ?

### ISSUE THREAD

**Issue by evanjmg** [benjamincharity/angular-flickity#66]
Is there a reason why sourcemaps are included in the min.js? This makes the bundle unnecessarily large

**Comment by benjamincharity** [comment]
I think this was the first webpack project I set up.. so most likely just a lack of knowledge. Good catch though. 

Just removed and bumped the version: https://github.com/benjamincharity/angular-flickity/releases/tag/v3.1.0
