### ISSUE TITLE
Can not inject bc.Flickity

### ISSUE THREAD

**Issue by bujardeari** [benjamincharity/angular-flickity#72]
I am struggling with this for 2 days now, i installed flickity first with npm , and it was not working, then again with bower and made the changes you say but again the same problem,Module 'bc.Flickity' is not available

**Comment by benjamincharity** [comment]
Sorry to hear you are having troubles. I know how frustrating that can be!

Can you provide some context around your project? Is it using a bundler such as Webpack etc to pull all your scripts together? Or are you manually adding script tags to your HTML page?

Also, posting some of your code might help (such as where you are including this module into your project etc).

**Comment by benjamincharity** [comment]
Closing for lack of information. Feel free to open a new issue with more information if you are still having trouble!
