### ISSUE TITLE
angular 1.6.1

### ISSUE THREAD

**Issue by speedgoofy** [benjamincharity/angular-flickity#73]
Issues with angular 1.6.1 .. autoPlay: true was the main one I found in my very limited testing. 

Quick test:  Use your simple demo @ http://codepen.io/anon/pen/RoXaXy and change the 1.5 cdn out with 1.6.1 link below. You’ll notice  the slides will no longer play. This is a great wrapper though! Thanks!

https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.min.js

**Comment by benjamincharity** [comment]
Thanks for pointing this out. I've been deep in the Angular2 world for work so haven't even tried this library with 1.6.x.  I'll try to find some time to look into this. 👍

**Comment by zurie** [comment]
Have you had a chance to use something like this in angular2.   A rewrite in typescript might be a fun side project ;)

**Comment by benjamincharity** [comment]
I've actually just finished my second Angular2 project, so I finally feel competent enough to start rebuilding this for ng2. Finishing up a hard deadline this week, so I'm hoping I can put some time into this bug and the ng2 version in the coming weeks 👍

**Comment by benjamincharity** [comment]
Ok, it seems a bug popped up around the merging of user options with default options. Fixed in `3.1.1`. https://github.com/benjamincharity/angular-flickity/releases/tag/v3.1.1

Thanks for reporting! 🙇
