### ISSUE TITLE
angular-flickity refers to `Flickity` node_modules, which should be `flickity`

### ISSUE THREAD

**Issue by nkahoang** [benjamincharity/angular-flickity#77]
The bundle refers to the flickity node_modules as `Flickity`. 

This will work fine on Windows or macOS as their file system is case-insensitive by default.

However, on a Linux box, an error will be raised as the actual package for flickity is `flickity` (lower case f)

**Comment by benjamincharity** [comment]
Thanks for pointing this out.. I hadn't even thought about this.

**Comment by shashilo** [comment]
@benjamincharity When do you think you'll take care of this issue? We're using the library but cannot push to our production environment until this is fixed. Thanks!

**Comment by dtesta** [comment]
New related issue: #87
